### ISSUE TITLE
Add hints and guesses section in the application

### ISSUE THREAD

**Issue by zoneboy** [Reepeecheep/NumberGuesser#8]
# Introduction

[Number guesser](https://f-droid.org/en/packages/com.numguesser.tonio_rpchp.numberguesser/) is a mobile game where users try to guess a number. The computer choose a number between 0-100 which the player must guess in 5 attempts.

# Components

My suggestion is on the
* Gameplay interface

# Proposal

> The gameplay interface currently have a place to input your guessed number, the number of lines remaining and little explanation.

I propose the addition of a

**Guesses section**- This will include all the guesses made and how close they were to the correct number. Although, that pops up when a user type in the guessed number, it is not good enough. It pops up and disappears is not very good.

**Hints section** - This section will show hints related to the correct number as the guesses are being entered. There should be an option to disable hints too. The hints given on guesses entered can be based on

* Odds or even numbers
* Product of the digits
* Sum of the digits and so on.

This will be further explained in the Mockups below.

# Mockups/Examples
![20190220_151306.jpg](https://cdn.steemitimages.com/DQmX3TiXx1269QfKK9Lf67xUWa47ec2C8MPh7nW1B9sudyM/20190220_151306.jpg)
The above is how I want the gameplay interface to be modified. You can see the Hints and the Guesses section in the modified interface.

![20190220_151157.png](https://cdn.steemitimages.com/DQmZWQVrDeVQasu1fcYqqL4YzcKg1VMxchF1zqn6ViyLy7X/20190220_151157.png)
This is the show hints button that can be toggled on and off as the case may be.
# Benefits

**Guess section**- The addition of this section will be highly beneficial to the application. It will enable the players to see their past guesses and how close or far those guesses were to the correct number. This can let them do the calculation in getting the correct number. This is much better than the current system where both the guessed number and information given pop up and disappears immediately.

**Hint Section**- This will be a major addition and will see increase in users utilizing the game. This section will show hints related to the correct number. The hints coupled with the guessed number informations can be used to narrow down the numbers list in a bid to get the correct number. It will make the game more appealing and addictive. Players will know that they have a chance of winning if they can compare the hints information and guesses section information, then find the possible answer between both. 

Giving users the ability to turn hints on and off gives more flexibility. It allows users to test if they can get the correct number without any help from the system.

# Conclusion

Implementation of these features will make the game addictive and will see more people getting on to play it. It will also help players to put their brain into work by looking for the correct number with the informations gotten from the 2 sections.

**Comment by Reepeecheep** [comment]
Thanks @zoneboy
